# Generated by Django 4.1.1 on 2022-10-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coctel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.TextField(max_length=50, verbose_name="Nombre Coctel"),
                ),
                ("sinoAlcohol", models.BooleanField(default="True")),
            ],
        ),
        migrations.CreateModel(
            name="Diluidores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.TextField(max_length=50, verbose_name="Nombre del diluidor"),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
            ],
        ),
        migrations.CreateModel(
            name="Licor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.TextField(max_length=50, verbose_name="Nombre del licor"),
                ),
                (
                    "cantidad",
                    models.IntegerField(verbose_name="Cantidad en ml del licor"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre usuario"),
                ),
                (
                    "apellido",
                    models.CharField(max_length=50, verbose_name="Apellido usuario"),
                ),
                (
                    "nombreDeUsuario",
                    models.CharField(max_length=50, verbose_name="Nombre de usuario"),
                ),
                (
                    "fechaNacimiento",
                    models.DateField(verbose_name="Fecha nacimiento usuario"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favoritos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idCoctel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.coctel",
                    ),
                ),
                (
                    "idUsuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentesCoctel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idCoctel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.coctel",
                    ),
                ),
                (
                    "idDiluidores",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.diluidores",
                    ),
                ),
                (
                    "idLicorBase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.licor",
                    ),
                ),
            ],
        ),
    ]
