# Generated by Django 4.1.1 on 2022-10-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="coctel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(blank=True)),
                (
                    "sinoAlcohol",
                    models.CharField(
                        choices=[
                            ("Si", "Cocteles Con alcohol"),
                            ("No", "Cocteles Sin alchohol"),
                        ],
                        default="Si",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="componente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre componente"),
                ),
                (
                    "tipoComponente",
                    models.CharField(max_length=50, verbose_name="Tipo componente"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre usuario"),
                ),
                (
                    "apellido",
                    models.CharField(max_length=50, verbose_name="Apellido usuario"),
                ),
                (
                    "nombreDeUsuario",
                    models.CharField(max_length=50, verbose_name="Nombre de usuario"),
                ),
                (
                    "fechaNacimiento",
                    models.DateField(verbose_name="Fecha nacimiento usuario"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="favoritos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idCoctel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.coctel",
                    ),
                ),
                (
                    "idUsuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coctel",
            name="idComponente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cocktails.componente",
            ),
        ),
    ]
