# Generated by Django 4.1.1 on 2022-10-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del coctel"),
                ),
                (
                    "cantidad",
                    models.CharField(
                        max_length=50, verbose_name="Cantidad del alcohol"
                    ),
                ),
                (
                    "tipoIngrediente",
                    models.CharField(max_length=50, verbose_name="Tipo componente"),
                ),
            ],
        ),
        migrations.RemoveField(model_name="coctel", name="idComponente",),
        migrations.DeleteModel(name="componente",),
        migrations.AddField(
            model_name="ingrediente",
            name="idCoctel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cocktails.coctel",
            ),
        ),
    ]
